export default days = {
    ['Whiro']: 'an unpleasant day, the new moon appears.',
    ['Tirea']: 'the moon is very small.',
    ['Hoata']: 'a pleasing day, the moon is still small.',
    ['Ōuenuku']: 'get to work! A good night for eeling.',
    ['Okoro']: 'a pleasing day in the afternoon, good for eeling at night.',
    ['Tamat[e]a-ngana']: 'unpleasant weather, the sea is rough.',
    ['Tamatea-kai-ariki']: 'the weather improves.',
    ['Huna']: 'bad weather, food products suffer.',
    ['Ari-roa']: 'favourable for spearing eels.',
    ['Maure']: 'a fine, desirable day.',
    ['Māwharu']: 'crayfish are taken on this day.',
    ['Ohua']: 'a good day for working.',
    ['Hotu']: 'an unpleasant day, the sea is rough.',
    ['Atua']: 'an abominable day.',
    ['Turu']: 'a day to collect food from the sea.',
    ['Rākau-nui']: 'the moon is filled out, produce from the sea is the staple food.',
    ['Rākau-matohi']: 'a fine day, the moon now wanes.',
    ['Takirau']: 'fine weather during the morning.',
    ['Oike']: 'the afternoon is favourable.',
    ['Korekore-te-whiwhia']: 'a bad day.',
    ['Korekore-te-rawea']: 'a bad day.',
    ['Korekore-hahani']: 'a fairly good day.',
    ['Tangaroa-ā-mua']: 'a good day for fishing.',
    ['Tangaroa-ā-roto']: 'a good day for fishing.',
    ['Tangaroa-kiokio']: 'an excellent day for fishing, a misty aspect prevails on land.',
    ['Ōtāne']: 'a good day, and a good night for eeling.',
    ['Ōrongonui']: 'a desirable day, the īnanga (whitebait) migrate.',
    ['Mauri']: 'the morning is fine, the moon has now darkened.',
    ['Ōmutu']: 'a bad day.',
    ['Mutuwhenua']: 'an exceedingly bad day, the moon has expired.'
}
